// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe_extend.proto

#ifndef PROTOBUF_caffe_5fextend_2eproto__INCLUDED
#define PROTOBUF_caffe_5fextend_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "caffe/proto/caffe.pb.h"
// @@protoc_insertion_point(includes)

namespace caffe_ext {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_caffe_5fextend_2eproto();
void protobuf_InitDefaults_caffe_5fextend_2eproto();
void protobuf_AssignDesc_caffe_5fextend_2eproto();
void protobuf_ShutdownFile_caffe_5fextend_2eproto();

class ImgBBoxAnnoDatum;

// ===================================================================

class ImgBBoxAnnoDatum : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:caffe_ext.ImgBBoxAnnoDatum) */ {
 public:
  ImgBBoxAnnoDatum();
  virtual ~ImgBBoxAnnoDatum();

  ImgBBoxAnnoDatum(const ImgBBoxAnnoDatum& from);

  inline ImgBBoxAnnoDatum& operator=(const ImgBBoxAnnoDatum& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImgBBoxAnnoDatum& default_instance();

  static const ImgBBoxAnnoDatum* internal_default_instance();

  void Swap(ImgBBoxAnnoDatum* other);

  // implements Message ----------------------------------------------

  inline ImgBBoxAnnoDatum* New() const { return New(NULL); }

  ImgBBoxAnnoDatum* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImgBBoxAnnoDatum& from);
  void MergeFrom(const ImgBBoxAnnoDatum& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ImgBBoxAnnoDatum* other);
  void UnsafeMergeFrom(const ImgBBoxAnnoDatum& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .caffe.Datum img_datum = 1;
  bool has_img_datum() const;
  void clear_img_datum();
  static const int kImgDatumFieldNumber = 1;
  const ::caffe::Datum& img_datum() const;
  ::caffe::Datum* mutable_img_datum();
  ::caffe::Datum* release_img_datum();
  void set_allocated_img_datum(::caffe::Datum* img_datum);

  // repeated int32 label = 2;
  int label_size() const;
  void clear_label();
  static const int kLabelFieldNumber = 2;
  ::google::protobuf::int32 label(int index) const;
  void set_label(int index, ::google::protobuf::int32 value);
  void add_label(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      label() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_label();

  // repeated float x_min = 3;
  int x_min_size() const;
  void clear_x_min();
  static const int kXMinFieldNumber = 3;
  float x_min(int index) const;
  void set_x_min(int index, float value);
  void add_x_min(float value);
  const ::google::protobuf::RepeatedField< float >&
      x_min() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_x_min();

  // repeated float y_min = 4;
  int y_min_size() const;
  void clear_y_min();
  static const int kYMinFieldNumber = 4;
  float y_min(int index) const;
  void set_y_min(int index, float value);
  void add_y_min(float value);
  const ::google::protobuf::RepeatedField< float >&
      y_min() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_y_min();

  // repeated float x_max = 5;
  int x_max_size() const;
  void clear_x_max();
  static const int kXMaxFieldNumber = 5;
  float x_max(int index) const;
  void set_x_max(int index, float value);
  void add_x_max(float value);
  const ::google::protobuf::RepeatedField< float >&
      x_max() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_x_max();

  // repeated float y_max = 6;
  int y_max_size() const;
  void clear_y_max();
  static const int kYMaxFieldNumber = 6;
  float y_max(int index) const;
  void set_y_max(int index, float value);
  void add_y_max(float value);
  const ::google::protobuf::RepeatedField< float >&
      y_max() const;
  ::google::protobuf::RepeatedField< float >*
      mutable_y_max();

  // @@protoc_insertion_point(class_scope:caffe_ext.ImgBBoxAnnoDatum)
 private:
  inline void set_has_img_datum();
  inline void clear_has_img_datum();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > label_;
  ::google::protobuf::RepeatedField< float > x_min_;
  ::google::protobuf::RepeatedField< float > y_min_;
  ::google::protobuf::RepeatedField< float > x_max_;
  ::google::protobuf::RepeatedField< float > y_max_;
  ::caffe::Datum* img_datum_;
  friend void  protobuf_InitDefaults_caffe_5fextend_2eproto_impl();
  friend void  protobuf_AddDesc_caffe_5fextend_2eproto_impl();
  friend void protobuf_AssignDesc_caffe_5fextend_2eproto();
  friend void protobuf_ShutdownFile_caffe_5fextend_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<ImgBBoxAnnoDatum> ImgBBoxAnnoDatum_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ImgBBoxAnnoDatum

// required .caffe.Datum img_datum = 1;
inline bool ImgBBoxAnnoDatum::has_img_datum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImgBBoxAnnoDatum::set_has_img_datum() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImgBBoxAnnoDatum::clear_has_img_datum() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImgBBoxAnnoDatum::clear_img_datum() {
  if (img_datum_ != NULL) img_datum_->::caffe::Datum::Clear();
  clear_has_img_datum();
}
inline const ::caffe::Datum& ImgBBoxAnnoDatum::img_datum() const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  return img_datum_ != NULL ? *img_datum_
                         : *::caffe::Datum::internal_default_instance();
}
inline ::caffe::Datum* ImgBBoxAnnoDatum::mutable_img_datum() {
  set_has_img_datum();
  if (img_datum_ == NULL) {
    img_datum_ = new ::caffe::Datum;
  }
  // @@protoc_insertion_point(field_mutable:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  return img_datum_;
}
inline ::caffe::Datum* ImgBBoxAnnoDatum::release_img_datum() {
  // @@protoc_insertion_point(field_release:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  clear_has_img_datum();
  ::caffe::Datum* temp = img_datum_;
  img_datum_ = NULL;
  return temp;
}
inline void ImgBBoxAnnoDatum::set_allocated_img_datum(::caffe::Datum* img_datum) {
  delete img_datum_;
  img_datum_ = img_datum;
  if (img_datum) {
    set_has_img_datum();
  } else {
    clear_has_img_datum();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe_ext.ImgBBoxAnnoDatum.img_datum)
}

// repeated int32 label = 2;
inline int ImgBBoxAnnoDatum::label_size() const {
  return label_.size();
}
inline void ImgBBoxAnnoDatum::clear_label() {
  label_.Clear();
}
inline ::google::protobuf::int32 ImgBBoxAnnoDatum::label(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.label)
  return label_.Get(index);
}
inline void ImgBBoxAnnoDatum::set_label(int index, ::google::protobuf::int32 value) {
  label_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.label)
}
inline void ImgBBoxAnnoDatum::add_label(::google::protobuf::int32 value) {
  label_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.label)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ImgBBoxAnnoDatum::label() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.label)
  return label_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ImgBBoxAnnoDatum::mutable_label() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.label)
  return &label_;
}

// repeated float x_min = 3;
inline int ImgBBoxAnnoDatum::x_min_size() const {
  return x_min_.size();
}
inline void ImgBBoxAnnoDatum::clear_x_min() {
  x_min_.Clear();
}
inline float ImgBBoxAnnoDatum::x_min(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return x_min_.Get(index);
}
inline void ImgBBoxAnnoDatum::set_x_min(int index, float value) {
  x_min_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.x_min)
}
inline void ImgBBoxAnnoDatum::add_x_min(float value) {
  x_min_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.x_min)
}
inline const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::x_min() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return x_min_;
}
inline ::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_x_min() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return &x_min_;
}

// repeated float y_min = 4;
inline int ImgBBoxAnnoDatum::y_min_size() const {
  return y_min_.size();
}
inline void ImgBBoxAnnoDatum::clear_y_min() {
  y_min_.Clear();
}
inline float ImgBBoxAnnoDatum::y_min(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return y_min_.Get(index);
}
inline void ImgBBoxAnnoDatum::set_y_min(int index, float value) {
  y_min_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.y_min)
}
inline void ImgBBoxAnnoDatum::add_y_min(float value) {
  y_min_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.y_min)
}
inline const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::y_min() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return y_min_;
}
inline ::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_y_min() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return &y_min_;
}

// repeated float x_max = 5;
inline int ImgBBoxAnnoDatum::x_max_size() const {
  return x_max_.size();
}
inline void ImgBBoxAnnoDatum::clear_x_max() {
  x_max_.Clear();
}
inline float ImgBBoxAnnoDatum::x_max(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return x_max_.Get(index);
}
inline void ImgBBoxAnnoDatum::set_x_max(int index, float value) {
  x_max_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.x_max)
}
inline void ImgBBoxAnnoDatum::add_x_max(float value) {
  x_max_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.x_max)
}
inline const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::x_max() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return x_max_;
}
inline ::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_x_max() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return &x_max_;
}

// repeated float y_max = 6;
inline int ImgBBoxAnnoDatum::y_max_size() const {
  return y_max_.size();
}
inline void ImgBBoxAnnoDatum::clear_y_max() {
  y_max_.Clear();
}
inline float ImgBBoxAnnoDatum::y_max(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return y_max_.Get(index);
}
inline void ImgBBoxAnnoDatum::set_y_max(int index, float value) {
  y_max_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.y_max)
}
inline void ImgBBoxAnnoDatum::add_y_max(float value) {
  y_max_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.y_max)
}
inline const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::y_max() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return y_max_;
}
inline ::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_y_max() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return &y_max_;
}

inline const ImgBBoxAnnoDatum* ImgBBoxAnnoDatum::internal_default_instance() {
  return &ImgBBoxAnnoDatum_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe_ext

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_caffe_5fextend_2eproto__INCLUDED
