// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: caffe_extend.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "caffe_extend.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace caffe_ext {

namespace {

const ::google::protobuf::Descriptor* ImgBBoxAnnoDatum_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ImgBBoxAnnoDatum_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_caffe_5fextend_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_caffe_5fextend_2eproto() {
  protobuf_AddDesc_caffe_5fextend_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "caffe_extend.proto");
  GOOGLE_CHECK(file != NULL);
  ImgBBoxAnnoDatum_descriptor_ = file->message_type(0);
  static const int ImgBBoxAnnoDatum_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, img_datum_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, label_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, x_min_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, y_min_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, x_max_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, y_max_),
  };
  ImgBBoxAnnoDatum_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ImgBBoxAnnoDatum_descriptor_,
      ImgBBoxAnnoDatum::internal_default_instance(),
      ImgBBoxAnnoDatum_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, _has_bits_),
      -1,
      -1,
      sizeof(ImgBBoxAnnoDatum),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ImgBBoxAnnoDatum, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_caffe_5fextend_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ImgBBoxAnnoDatum_descriptor_, ImgBBoxAnnoDatum::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_caffe_5fextend_2eproto() {
  ImgBBoxAnnoDatum_default_instance_.Shutdown();
  delete ImgBBoxAnnoDatum_reflection_;
}

void protobuf_InitDefaults_caffe_5fextend_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::caffe::protobuf_InitDefaults_caffe_2eproto();
  ImgBBoxAnnoDatum_default_instance_.DefaultConstruct();
  ImgBBoxAnnoDatum_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_caffe_5fextend_2eproto_once_);
void protobuf_InitDefaults_caffe_5fextend_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_caffe_5fextend_2eproto_once_,
                 &protobuf_InitDefaults_caffe_5fextend_2eproto_impl);
}
void protobuf_AddDesc_caffe_5fextend_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_caffe_5fextend_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022caffe_extend.proto\022\tcaffe_ext\032\027caffe/p"
    "roto/caffe.proto\"~\n\020ImgBBoxAnnoDatum\022\037\n\t"
    "img_datum\030\001 \002(\0132\014.caffe.Datum\022\r\n\005label\030\002"
    " \003(\005\022\r\n\005x_min\030\003 \003(\002\022\r\n\005y_min\030\004 \003(\002\022\r\n\005x_"
    "max\030\005 \003(\002\022\r\n\005y_max\030\006 \003(\002", 184);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "caffe_extend.proto", &protobuf_RegisterTypes);
  ::caffe::protobuf_AddDesc_caffe_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_caffe_5fextend_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_caffe_5fextend_2eproto_once_);
void protobuf_AddDesc_caffe_5fextend_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_caffe_5fextend_2eproto_once_,
                 &protobuf_AddDesc_caffe_5fextend_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_caffe_5fextend_2eproto {
  StaticDescriptorInitializer_caffe_5fextend_2eproto() {
    protobuf_AddDesc_caffe_5fextend_2eproto();
  }
} static_descriptor_initializer_caffe_5fextend_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ImgBBoxAnnoDatum::kImgDatumFieldNumber;
const int ImgBBoxAnnoDatum::kLabelFieldNumber;
const int ImgBBoxAnnoDatum::kXMinFieldNumber;
const int ImgBBoxAnnoDatum::kYMinFieldNumber;
const int ImgBBoxAnnoDatum::kXMaxFieldNumber;
const int ImgBBoxAnnoDatum::kYMaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ImgBBoxAnnoDatum::ImgBBoxAnnoDatum()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_caffe_5fextend_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:caffe_ext.ImgBBoxAnnoDatum)
}

void ImgBBoxAnnoDatum::InitAsDefaultInstance() {
  img_datum_ = const_cast< ::caffe::Datum*>(
      ::caffe::Datum::internal_default_instance());
}

ImgBBoxAnnoDatum::ImgBBoxAnnoDatum(const ImgBBoxAnnoDatum& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:caffe_ext.ImgBBoxAnnoDatum)
}

void ImgBBoxAnnoDatum::SharedCtor() {
  _cached_size_ = 0;
  img_datum_ = NULL;
}

ImgBBoxAnnoDatum::~ImgBBoxAnnoDatum() {
  // @@protoc_insertion_point(destructor:caffe_ext.ImgBBoxAnnoDatum)
  SharedDtor();
}

void ImgBBoxAnnoDatum::SharedDtor() {
  if (this != &ImgBBoxAnnoDatum_default_instance_.get()) {
    delete img_datum_;
  }
}

void ImgBBoxAnnoDatum::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ImgBBoxAnnoDatum::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ImgBBoxAnnoDatum_descriptor_;
}

const ImgBBoxAnnoDatum& ImgBBoxAnnoDatum::default_instance() {
  protobuf_InitDefaults_caffe_5fextend_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ImgBBoxAnnoDatum> ImgBBoxAnnoDatum_default_instance_;

ImgBBoxAnnoDatum* ImgBBoxAnnoDatum::New(::google::protobuf::Arena* arena) const {
  ImgBBoxAnnoDatum* n = new ImgBBoxAnnoDatum;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ImgBBoxAnnoDatum::Clear() {
// @@protoc_insertion_point(message_clear_start:caffe_ext.ImgBBoxAnnoDatum)
  if (has_img_datum()) {
    if (img_datum_ != NULL) img_datum_->::caffe::Datum::Clear();
  }
  label_.Clear();
  x_min_.Clear();
  y_min_.Clear();
  x_max_.Clear();
  y_max_.Clear();
  _has_bits_.Clear();
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool ImgBBoxAnnoDatum::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:caffe_ext.ImgBBoxAnnoDatum)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .caffe.Datum img_datum = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_img_datum()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_label;
        break;
      }

      // repeated int32 label = 2;
      case 2: {
        if (tag == 16) {
         parse_label:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_label())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_label())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_label;
        if (input->ExpectTag(29)) goto parse_x_min;
        break;
      }

      // repeated float x_min = 3;
      case 3: {
        if (tag == 29) {
         parse_x_min:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 29, input, this->mutable_x_min())));
        } else if (tag == 26) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_x_min())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_x_min;
        if (input->ExpectTag(37)) goto parse_y_min;
        break;
      }

      // repeated float y_min = 4;
      case 4: {
        if (tag == 37) {
         parse_y_min:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 37, input, this->mutable_y_min())));
        } else if (tag == 34) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_y_min())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_y_min;
        if (input->ExpectTag(45)) goto parse_x_max;
        break;
      }

      // repeated float x_max = 5;
      case 5: {
        if (tag == 45) {
         parse_x_max:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 45, input, this->mutable_x_max())));
        } else if (tag == 42) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_x_max())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(45)) goto parse_x_max;
        if (input->ExpectTag(53)) goto parse_y_max;
        break;
      }

      // repeated float y_max = 6;
      case 6: {
        if (tag == 53) {
         parse_y_max:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 53, input, this->mutable_y_max())));
        } else if (tag == 50) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_y_max())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(53)) goto parse_y_max;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:caffe_ext.ImgBBoxAnnoDatum)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:caffe_ext.ImgBBoxAnnoDatum)
  return false;
#undef DO_
}

void ImgBBoxAnnoDatum::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:caffe_ext.ImgBBoxAnnoDatum)
  // required .caffe.Datum img_datum = 1;
  if (has_img_datum()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->img_datum_, output);
  }

  // repeated int32 label = 2;
  for (int i = 0; i < this->label_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->label(i), output);
  }

  // repeated float x_min = 3;
  for (int i = 0; i < this->x_min_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      3, this->x_min(i), output);
  }

  // repeated float y_min = 4;
  for (int i = 0; i < this->y_min_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      4, this->y_min(i), output);
  }

  // repeated float x_max = 5;
  for (int i = 0; i < this->x_max_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      5, this->x_max(i), output);
  }

  // repeated float y_max = 6;
  for (int i = 0; i < this->y_max_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      6, this->y_max(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:caffe_ext.ImgBBoxAnnoDatum)
}

::google::protobuf::uint8* ImgBBoxAnnoDatum::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:caffe_ext.ImgBBoxAnnoDatum)
  // required .caffe.Datum img_datum = 1;
  if (has_img_datum()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->img_datum_, false, target);
  }

  // repeated int32 label = 2;
  for (int i = 0; i < this->label_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->label(i), target);
  }

  // repeated float x_min = 3;
  for (int i = 0; i < this->x_min_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(3, this->x_min(i), target);
  }

  // repeated float y_min = 4;
  for (int i = 0; i < this->y_min_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(4, this->y_min(i), target);
  }

  // repeated float x_max = 5;
  for (int i = 0; i < this->x_max_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(5, this->x_max(i), target);
  }

  // repeated float y_max = 6;
  for (int i = 0; i < this->y_max_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteFloatToArray(6, this->y_max(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:caffe_ext.ImgBBoxAnnoDatum)
  return target;
}

size_t ImgBBoxAnnoDatum::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:caffe_ext.ImgBBoxAnnoDatum)
  size_t total_size = 0;

  // required .caffe.Datum img_datum = 1;
  if (has_img_datum()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->img_datum_);
  }
  // repeated int32 label = 2;
  {
    size_t data_size = 0;
    unsigned int count = this->label_size();
    for (unsigned int i = 0; i < count; i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->label(i));
    }
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->label_size());
    total_size += data_size;
  }

  // repeated float x_min = 3;
  {
    size_t data_size = 0;
    unsigned int count = this->x_min_size();
    data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->x_min_size());
    total_size += data_size;
  }

  // repeated float y_min = 4;
  {
    size_t data_size = 0;
    unsigned int count = this->y_min_size();
    data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->y_min_size());
    total_size += data_size;
  }

  // repeated float x_max = 5;
  {
    size_t data_size = 0;
    unsigned int count = this->x_max_size();
    data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->x_max_size());
    total_size += data_size;
  }

  // repeated float y_max = 6;
  {
    size_t data_size = 0;
    unsigned int count = this->y_max_size();
    data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->y_max_size());
    total_size += data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ImgBBoxAnnoDatum::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:caffe_ext.ImgBBoxAnnoDatum)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ImgBBoxAnnoDatum* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ImgBBoxAnnoDatum>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:caffe_ext.ImgBBoxAnnoDatum)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:caffe_ext.ImgBBoxAnnoDatum)
    UnsafeMergeFrom(*source);
  }
}

void ImgBBoxAnnoDatum::MergeFrom(const ImgBBoxAnnoDatum& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:caffe_ext.ImgBBoxAnnoDatum)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ImgBBoxAnnoDatum::UnsafeMergeFrom(const ImgBBoxAnnoDatum& from) {
  GOOGLE_DCHECK(&from != this);
  label_.UnsafeMergeFrom(from.label_);
  x_min_.UnsafeMergeFrom(from.x_min_);
  y_min_.UnsafeMergeFrom(from.y_min_);
  x_max_.UnsafeMergeFrom(from.x_max_);
  y_max_.UnsafeMergeFrom(from.y_max_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_img_datum()) {
      mutable_img_datum()->::caffe::Datum::MergeFrom(from.img_datum());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::UnknownFieldSet::MergeToInternalMetdata(
      from.unknown_fields(), &_internal_metadata_);
  }
}

void ImgBBoxAnnoDatum::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:caffe_ext.ImgBBoxAnnoDatum)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ImgBBoxAnnoDatum::CopyFrom(const ImgBBoxAnnoDatum& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:caffe_ext.ImgBBoxAnnoDatum)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ImgBBoxAnnoDatum::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void ImgBBoxAnnoDatum::Swap(ImgBBoxAnnoDatum* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ImgBBoxAnnoDatum::InternalSwap(ImgBBoxAnnoDatum* other) {
  std::swap(img_datum_, other->img_datum_);
  label_.UnsafeArenaSwap(&other->label_);
  x_min_.UnsafeArenaSwap(&other->x_min_);
  y_min_.UnsafeArenaSwap(&other->y_min_);
  x_max_.UnsafeArenaSwap(&other->x_max_);
  y_max_.UnsafeArenaSwap(&other->y_max_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ImgBBoxAnnoDatum::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ImgBBoxAnnoDatum_descriptor_;
  metadata.reflection = ImgBBoxAnnoDatum_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ImgBBoxAnnoDatum

// required .caffe.Datum img_datum = 1;
bool ImgBBoxAnnoDatum::has_img_datum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ImgBBoxAnnoDatum::set_has_img_datum() {
  _has_bits_[0] |= 0x00000001u;
}
void ImgBBoxAnnoDatum::clear_has_img_datum() {
  _has_bits_[0] &= ~0x00000001u;
}
void ImgBBoxAnnoDatum::clear_img_datum() {
  if (img_datum_ != NULL) img_datum_->::caffe::Datum::Clear();
  clear_has_img_datum();
}
const ::caffe::Datum& ImgBBoxAnnoDatum::img_datum() const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  return img_datum_ != NULL ? *img_datum_
                         : *::caffe::Datum::internal_default_instance();
}
::caffe::Datum* ImgBBoxAnnoDatum::mutable_img_datum() {
  set_has_img_datum();
  if (img_datum_ == NULL) {
    img_datum_ = new ::caffe::Datum;
  }
  // @@protoc_insertion_point(field_mutable:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  return img_datum_;
}
::caffe::Datum* ImgBBoxAnnoDatum::release_img_datum() {
  // @@protoc_insertion_point(field_release:caffe_ext.ImgBBoxAnnoDatum.img_datum)
  clear_has_img_datum();
  ::caffe::Datum* temp = img_datum_;
  img_datum_ = NULL;
  return temp;
}
void ImgBBoxAnnoDatum::set_allocated_img_datum(::caffe::Datum* img_datum) {
  delete img_datum_;
  img_datum_ = img_datum;
  if (img_datum) {
    set_has_img_datum();
  } else {
    clear_has_img_datum();
  }
  // @@protoc_insertion_point(field_set_allocated:caffe_ext.ImgBBoxAnnoDatum.img_datum)
}

// repeated int32 label = 2;
int ImgBBoxAnnoDatum::label_size() const {
  return label_.size();
}
void ImgBBoxAnnoDatum::clear_label() {
  label_.Clear();
}
::google::protobuf::int32 ImgBBoxAnnoDatum::label(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.label)
  return label_.Get(index);
}
void ImgBBoxAnnoDatum::set_label(int index, ::google::protobuf::int32 value) {
  label_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.label)
}
void ImgBBoxAnnoDatum::add_label(::google::protobuf::int32 value) {
  label_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.label)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
ImgBBoxAnnoDatum::label() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.label)
  return label_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
ImgBBoxAnnoDatum::mutable_label() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.label)
  return &label_;
}

// repeated float x_min = 3;
int ImgBBoxAnnoDatum::x_min_size() const {
  return x_min_.size();
}
void ImgBBoxAnnoDatum::clear_x_min() {
  x_min_.Clear();
}
float ImgBBoxAnnoDatum::x_min(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return x_min_.Get(index);
}
void ImgBBoxAnnoDatum::set_x_min(int index, float value) {
  x_min_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.x_min)
}
void ImgBBoxAnnoDatum::add_x_min(float value) {
  x_min_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.x_min)
}
const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::x_min() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return x_min_;
}
::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_x_min() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.x_min)
  return &x_min_;
}

// repeated float y_min = 4;
int ImgBBoxAnnoDatum::y_min_size() const {
  return y_min_.size();
}
void ImgBBoxAnnoDatum::clear_y_min() {
  y_min_.Clear();
}
float ImgBBoxAnnoDatum::y_min(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return y_min_.Get(index);
}
void ImgBBoxAnnoDatum::set_y_min(int index, float value) {
  y_min_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.y_min)
}
void ImgBBoxAnnoDatum::add_y_min(float value) {
  y_min_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.y_min)
}
const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::y_min() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return y_min_;
}
::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_y_min() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.y_min)
  return &y_min_;
}

// repeated float x_max = 5;
int ImgBBoxAnnoDatum::x_max_size() const {
  return x_max_.size();
}
void ImgBBoxAnnoDatum::clear_x_max() {
  x_max_.Clear();
}
float ImgBBoxAnnoDatum::x_max(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return x_max_.Get(index);
}
void ImgBBoxAnnoDatum::set_x_max(int index, float value) {
  x_max_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.x_max)
}
void ImgBBoxAnnoDatum::add_x_max(float value) {
  x_max_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.x_max)
}
const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::x_max() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return x_max_;
}
::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_x_max() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.x_max)
  return &x_max_;
}

// repeated float y_max = 6;
int ImgBBoxAnnoDatum::y_max_size() const {
  return y_max_.size();
}
void ImgBBoxAnnoDatum::clear_y_max() {
  y_max_.Clear();
}
float ImgBBoxAnnoDatum::y_max(int index) const {
  // @@protoc_insertion_point(field_get:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return y_max_.Get(index);
}
void ImgBBoxAnnoDatum::set_y_max(int index, float value) {
  y_max_.Set(index, value);
  // @@protoc_insertion_point(field_set:caffe_ext.ImgBBoxAnnoDatum.y_max)
}
void ImgBBoxAnnoDatum::add_y_max(float value) {
  y_max_.Add(value);
  // @@protoc_insertion_point(field_add:caffe_ext.ImgBBoxAnnoDatum.y_max)
}
const ::google::protobuf::RepeatedField< float >&
ImgBBoxAnnoDatum::y_max() const {
  // @@protoc_insertion_point(field_list:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return y_max_;
}
::google::protobuf::RepeatedField< float >*
ImgBBoxAnnoDatum::mutable_y_max() {
  // @@protoc_insertion_point(field_mutable_list:caffe_ext.ImgBBoxAnnoDatum.y_max)
  return &y_max_;
}

inline const ImgBBoxAnnoDatum* ImgBBoxAnnoDatum::internal_default_instance() {
  return &ImgBBoxAnnoDatum_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace caffe_ext

// @@protoc_insertion_point(global_scope)
